services:
  web:
    image: wallesonnn/festa-com-ia:${IMAGE_TAG:-latest}
    container_name: festa-com-ia
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.festa-com-ia.rule=Host(`festacomia.elizax.cloud`)"
      - "traefik.http.routers.festa-com-ia.entrypoints=websecure"
      - "traefik.http.routers.festa-com-ia.tls=true"
      - "traefik.http.routers.festa-com-ia.tls.certresolver=lets-encrypt"
      - "traefik.http.services.festa-com-ia.loadbalancer.server.port=3000"

networks:
  web:
    external: true
